### ISSUE TITLE
Table NEWSLETTER_CATEGORY does not exist

### ISSUE THREAD

**Issue by dcbroeder** [rotterdam-cs/rcsnewsletter-portlet#1]
When I install (successfully from lpkg) the newsletter portlet on a Liferay 6.2 EE SP11 (tomcat bundle) + Oracle 11g R2, some tables are not created by default : 
![tabledoesnotexists](https://cloud.githubusercontent.com/assets/1499347/7809049/bc18806a-0397-11e5-8983-7fdcf0eb368c.png)

For example when I try to add a newsletter list :
![image](https://cloud.githubusercontent.com/assets/1499347/7809081/03b6c738-0398-11e5-9778-ddd71e6ff2db.png)

The following trace appears : 
...
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: Could not execute JDBC batch update; SQL [insert into newsletter_category (companyid, groupid, adminEmail, description, fromEmail, fromName, greetingEmail, name, subscriptionEmail, unsubscriptionEmail, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.SQLGrammarException: Could not execute JDBC batch update
...
java.sql.BatchUpdateException: ORA-00942: table or view does not exist
...

**Comment by jmfrippiat** [comment]
Hi Daniel,

I've got the exact same issue and was wondering if you found a way to solve it.
Thanks.

Best regards,

Jean-Michel

**Comment by kasbaoui** [comment]
The problem is that with Oracle Database the plugin doesn't create the tables newsletter_category and newsletter_registration_portlet_config due to some annotations. To solve you have to:
1) Change all the @Type(type="text") to @Lob in the [...].newsletter.core.model.NewsletterCategory
2) Change the table name [newsletter_registration_portlet_config] to a shorter one, example [newsletter_registration] in the [...].newsletter.core.model.RegistrationConfig
This will create correctly the tables in the Oracle scheme. After that, you will face some queries errors, to fix them you will have to:
3) In the [...].newsletter.core.service.NewsletterSubscriptorServiceImpl.java in the methods [findAllByStatusAndCategoryCountAndCriteria] and [findAllByStatusAndCategoryCount] change the sql sentences [sql += " GROUP BY o.id) as count_inner_query";] to [sql += " GROUP BY o.id) count_inner_query";] and the return value cast from [return ((BigInteger)query.uniqueResult()).intValue();] to [return (BigDecimal)query.uniqueResult()).intValue();]
